### ISSUE TITLE
Resource providers not registered

### ISSUE THREAD

**Issue by jomuld** [Microsoft/MCW-Enterprise-ready-cloud#14]
When running this query, 
```
 Get-AzureRmResourceProvider `
>>     | Select-Object ProviderNamespace, ResourceTypes `
>>     | Format-List
```

the output does not contain Microsoft.Compute (for example) and thus people get confused at the next step of adding these to the restricting policy. 

The reason for Microsoft.Compute being absent is that this resource provider is not yet registered in the subscription because it never had any VM in it. 

Pic without Microsoft.Compute.
![image](https://user-images.githubusercontent.com/39297853/46705998-09f90a00-cbe7-11e8-8994-5c497547c693.png)

Pic with solution
![image](https://user-images.githubusercontent.com/39297853/46706037-44fb3d80-cbe7-11e8-8da4-e9bed5e04645.png)
-> Register resource providers with the subscription.

Thanks!
Joost

**Comment by mwasham** [comment]
addressed in Nov update
