### ISSUE TITLE
Typo error in PowerShell command

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-Enterprise-ready-cloud#15]
There is error in powershell command in Exercise 1 - task 2.1
Command is Login-AzureRmAccount -Subscription "{subscription name or id}" which would be Login-AzureRmAccount -SubscriptionId "{subscription name or id}". Id is missing -SubscriptionId switch.

https://github.com/Microsoft/MCW-Enterprise-ready-cloud/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Enterprise-ready%20cloud.md#task-2-apply-the-service-catalog-policy

**Comment by akn9050** [comment]
Hi Michael, I submitted a PR on this please review and merge.

**Comment by mwasham** [comment]
No longer needed - switched to cloud shell.
