### ISSUE TITLE
Ready for QC

### ISSUE THREAD

**Issue by mwasham** [Microsoft/MCW-Enterprise-ready-cloud#19]

**Comment by DawnmarieDesJardins** [comment]
Thanks for narrowing that down for me.  It's not ready for QC, it needs to be sent for SME review.  With the new process, I need one PR to avoid confusion, I still see two.  Please merge the two PRs into one so I can send a review email.

**Comment by ciphertxt** [comment]
Single PR has been created at https://github.com/Microsoft/MCW-Enterprise-ready-cloud/pull/20. The extra branches have also been cleaned up.

**Comment by DawnmarieDesJardins** [comment]
Closing. handled with creation of PR #20
