### ISSUE TITLE
Lab guide pre-reqs wrong

### ISSUE THREAD

**Issue by jtuliani** [Microsoft/MCW-Enterprise-ready-cloud#25]
The Lab guide prerequisites say you need Visual Studio (or deploy a VM with Visual Studio if you don't have it). But the lab never uses Visual Studio, so this is not needed after all.

**Comment by DawnmarieDesJardins** [comment]
Thank you!  Marking this issue for correction during our next scheduled update

**Comment by ciphertxt** [comment]
Closing. This has been addressed in the May 2019 Update
