### ISSUE TITLE
Suggested updates to WDS

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Enterprise-ready-cloud#26]
Use
 - Blueprints
 - Azure Policy for auditing VM password policy (inside the VM)
 - Possibly, Managed Applications for Service Catalog

**Comment by jtuliani** [comment]
I also suggest we strip the networking elements (ExpressRoute set up etc) to make space for the other governance items. Make this MCW totally focused on Governance, remove everything else. ER for example is covered in the Enterprise-Class Networking MCW.

**Comment by yinghli** [comment]
Some comments on networking parts:
1.	For whiteboard, networking design need a high-level topology to tell customer what the target is. Current design is like Azure feature list, but from customer perspective, they don’t know how those things working together. 
2.	For hands on lab, it is just a P2S VPN implementation, I don’t see any relation with whiteboard design and customer requirement.

**Comment by ChongRX78** [comment]
Must aligned to Cloud Adoption Framework: https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/overview

Click on "Implementing the Five Disciplines of Cloud Governance" on the left. The customer requirements in this MCW should align to scenarios being described under this.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan,
Please review open issues #25  and #26 and pull request #24 during this update and incorporate as needed.

**Comment by DawnmarieDesJardins** [comment]
@jtuliani 
Hi Jonathan,
We have lead sign-off to move forward with this update.
Thanks, Dawnmarie

**Comment by ciphertxt** [comment]
- #24 looks good. I'll have to run it all, but in principle, the updates to the Az module are needed.
- #25 should be incorporated as well. I think that VM was a throwback to when all of the VMs were provisioned with Visual Studio across all of the MCWs.
- For this one (#26):
  - Drop all of the existing content (or as much as makes sense) related to networking in the WDS/Lab. As @jtuliani pointed out, that is covered very well in other MCWs. I think that means we wouldn't have much to address w/ @yinghli's comment above, except in regards to updating to account for networking components from CAF (such as a DMZ Blueprint)
  - Add coverage for Azure Blueprints, new Policy, etc. I think we can align this to CAF and the Large Enterprise Journey (https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/governance/journeys/large-enterprise/overview) which would also allow us to introduce the Five Disciplines of Cloud Governance as @ChongRX78 called out. 
  - Update the lab to remove existing networking components and bring in Blueprints. This probably changes exercise #3 the most as the creation of resources for the E-Commerce team will (hopefully) mostly be driven out of ARM templates and Blueprint artifacts. (https://github.com/Microsoft/MCW-Enterprise-ready-cloud/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Enterprise-ready%20cloud.md#exercise-3-create-the-environment-for-the-e-commerce-team)

@DawnmarieDesJardins / @Jeff-Opsgility  - Can we get SME's to review and provide feedback/approval?

**Comment by DawnmarieDesJardins** [comment]
Closing issue, resolved in May 2019 update
