### ISSUE TITLE
May 2019 Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Enterprise-ready-cloud#27]
Hello,
This workshop is scheduled for a May 2019 update.  Please review open issues #25  and #26 and pull request #24 then give your suggested updates for SME review.

**SME's - please review issue  #26 Suggested updates to WDS by jtuliani and comment there moving forward.  

Thanks,
Dawnmarie

**Comment by ciphertxt** [comment]
Specific suggestions at https://github.com/Microsoft/MCW-Enterprise-ready-cloud/issues/26#issuecomment-483664256

**Comment by DawnmarieDesJardins** [comment]
Closing issue, resolved in May 2019 update merge
