### ISSUE TITLE
Change History is now available via the Activity Log

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Enterprise-ready-cloud#30]
In the WDS, Security Baseline, Q1

Trainer guide describes how to access the resource change history via Azure Policy, and calls out that it's not included in the Activity Log. That has now changed--Change History IS now part of the Activity Log.

The WDS should be updated to reflect this.

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding Paul for visibility

**Comment by DawnmarieDesJardins** [comment]
Labeling this issue as an enhancement for the next test/fix-update.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete.  Addressed in Oct 2019 test/fix merge.
