### ISSUE TITLE
Fix the script in Exercise 2 Task3.3 by removing guid for $groupObjectId

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Enterprise-ready-cloud#31]
Please fix the script in [Exercise 2 Task3.3](https://github.com/microsoft/MCW-Enterprise-ready-cloud/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Enterprise-ready%20cloud.md#task-3-enable-a-business-unit-administrator-for-the-subscription).

Existing command is $groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id.Guid  >>  $groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id.guid

It should be $groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id.Guid  >>  $groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Hello,
Please review/respond.
Thanks, Dawnmarie

**Comment by daveRendon** [comment]
Remove ".Guid"on line 7:
//before
$groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id.Guid  

//after

$groupObjectId = (Get-AzADGroup -SearchString $AdGroupName).Id

that should work, our class went through same issue and it was resolved by removing .Guid

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility 
Adding Paul for visibility - please review/advise.

**Comment by paulopsgility** [comment]
As pointed out, this was a simple fix. This was actually a workaround for a PowerShell cmdlet bug that has been fixed now.
