### ISSUE TITLE
Add comment on avoiding 'Classic' in lab

### ISSUE THREAD

**Issue by jtuliani** [microsoft/MCW-Enterprise-ready-cloud#36]
In the lab, when setting up the policy initiative, it's very easy to accidentally select the 'Classic' version of virtual networks / virtual machines, and very hard to detect afterwards that you have done so.

Have seen several students hit this issue.

Lab guide should add some text to help warn students of this potential trap.

**Comment by DawnmarieDesJardins** [comment]
Thanks for the tip Jonathan!
I'm going to mark this as an enhancement for the next update or test/fix.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of March 2020 test/fix.
