### ISSUE TITLE
Blueprint assignment still failsafter service catalogue update...

### ISSUE THREAD

**Issue by fawohlsc** [microsoft/MCW-Enterprise-ready-cloud#38]
... due to a typo. The **P** in Blueprint must be lower case, so "Microsoft.Blue**p**rint/blueprintAssignments/*". See [ Task 3: Update the Service catalog policy to allow blueprint assignments](https://github.com/microsoft/MCW-Enterprise-ready-cloud/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Enterprise-ready%20cloud.md#task-3-update-the-service-catalog-policy-to-allow-blueprint-assignments) - `{
    "source": "action",
    "like": "Microsoft.BluePrint/blueprintAssignments/*"
}`

**Comment by paulopsgility** [comment]
@fawohlsc thank you for catching this. Fix implemented.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge #39
