### ISSUE TITLE
unable to create budget

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-Enterprise-ready-cloud#41]
Exercise 4 : Task 3: step 6 , I am unable to create budget

**Comment by paulopsgility** [comment]
@Gvashi Can you give us some more information here? 

Also, Ex4, Task 3, Step 6 isn't the step that creates the budget. We just recently updated this repo with the March 2020 test/fix so please make sure you are using the new version.

**Comment by Gvashi** [comment]
Ex4, Task 3, Step 8, while adding the email it is showing error

**Comment by DawnmarieDesJardins** [comment]
@paulopsgility @mwasham 
Please review/advise.

**Comment by paulopsgility** [comment]
@Gvashi  So were you running the old version of the lab and then switched over to the new instructions and just found your spot in the lab or did you redo the lab using the new instructions? 

What error are you seeing seeing and specifically, what were you doing when it occurred? You are setting a number of items on this blade, then you set some other configurations after that.

Thanks, Paul

**Comment by DawnmarieDesJardins** [comment]
No response from originator.  Closing issue, please reopen if necessary.
