### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by paulopsgility** [microsoft/MCW-Enterprise-ready-cloud#42]
Here are our suggested updates for the June 2020 update. Please add any other suggestions or feedback to this issue.

- Update diagrams to use new Azure icons
- Sync policies with between lab and WDS (use built-in policies instead of custom)
- Change Blueprint to show resource group level artifacts 
- Change Blueprint to deploy at resource group scope instead of subscription-level scope
- Verify that Cost Management is fixed for use in Azure Pass, if not, add warning in lab indicating that that part of the lab will not work in Azure Pass.

**Comment by DawnmarieDesJardins** [comment]
This June 2020 update has been changed to a June test/fix.  Closing update issue.
