### ISSUE TITLE
Exercise1/Task5/Subtask2/Step3 and Step7 

### ISSUE THREAD

**Issue by rajredd** [microsoft/MCW-Enterprise-ready-cloud#44]
Exercise1/Task5/Subtask2/Step3:
3. Under Available Definitions, find the Restrict Resource Name Suffix policy definition created in Step 2.

>>  I did not find "Available Definition" in this step, instead, 

![image](https://user-images.githubusercontent.com/37375319/100530496-d9a6c800-31c0-11eb-952e-16fde6850abf.png)

7. Once you've added each resource type, select Save.

>> there was no Save button. 

![image](https://user-images.githubusercontent.com/37375319/100530505-ee835b80-31c0-11eb-9821-94785154a7bb.png)

**Comment by rajredd** [comment]
I performed the following step, 

Subtask 4: Test the naming convention policy
Attempt to create a permitted resource, in a permitted location, with a non-permitted name. For example, create a virtual network within the PolicyTestRG resource group named erc-network in the East US region. This should be rejected by the Resource Naming Convention policy.

It seemed that I did not setup the initiative parameters; this test allowed "erc-network" be created, which should be rejected.

**Comment by DawnmarieDesJardins** [comment]
@rajredd 
Hello.  Thank you for your interest.  Unfortunately, this workshop is being retired effective 12/1/20 so we are unable to create a fix for you.  Please take a look at https://microsoftcloudworkshop.com for a complete library of workshops - there may be others that will meet your needs.
